language: python
sudo: false
matrix:
    include:
        - python: 2.7
        - python: 3.4
        - python: 3.6
addons:
  apt:
    packages:
    - libhdf5-serial-dev 
install:
  - pip install .[simulate]
  - pip install coveralls
  - pip install numpy
  - pip install git+https://github.com/INCF/ninemlcatalog
script:
  nosetests test/unittests --with-coverage --cover-package=nineml
after_success:
  coveralls
